### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by JeromeLydia** [liys666666/DoubleClick#4]
在Fragment无效果！

**Comment by liys666666** [comment]
Fragment是在Activity的onResume()之后加进去的吗？ 框架是在Activity首次走onResume()的时候遍历所有的View进行hook, 所以在Resume()之后加进去的控件是没有办法生效的， 这个版本暂时是这样的，如果有什么好的方法和建议可以提出来。

**Comment by liys666666** [comment]
目前能想到的办法：需要特殊处理的时候，手动调用一次，重新hook当前的activity，这样就解决问题了。老铁，你怎么看？


---原始邮件---
发件人: &quot;JeromeLydia&quot;<notifications@github.com&gt;
发送时间: 2019年8月30日(星期五) 下午4:52
收件人: &quot;liys666666/DoubleClick&quot;<DoubleClick@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [liys666666/DoubleClick] 兼容性问题 (#4)



在Fragment无效果！
 
&mdash;

**Comment by JeromeLydia** [comment]
具体怎么写哪？提供的有重新hook当前的activity的方法吗？

**Comment by liys666666** [comment]
这个版本暂时没有提供哦，下个版本更新，会处理这个问题，在这两天内会发布新的版本， 到时候会邮件通知你的.

**Comment by JeromeLydia** [comment]
好的，谢谢！

**Comment by liys666666** [comment]
更新到V2.0.2版本应该就可以了， 调用 ViewDoubleHelper.hookActivity(long time);  这个方法，time不传的话会使用默认值。 
可以考虑在Fragment里面onResume或其它时间调用， 如果在Activity中fragmentTransaction.commit()后面调用， 可能会失败， 因为Fragment还没来得及加到Activity中就开始hook了。 
如果还有问题， 可以继续提出来。

**Comment by JeromeLydia** [comment]
好的，非常感谢！




------------------ 原始邮件 ------------------
发件人: "liys"<notifications@github.com>;
发送时间: 2019年9月2日(星期一) 下午5:31
收件人: "liys666666/DoubleClick"<DoubleClick@noreply.github.com>;
抄送: "平常人"<913974295@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [liys666666/DoubleClick] 兼容性问题 (#4)




更新到V2.0.2版本应该就可以了， 调用 ViewDoubleHelper.hookActivity(long time);  这个方法，time不传的话会使用默认值。
 可以考虑在Fragment里面onResume或其它时间调用， 如果在Activity中fragmentTransaction.commit()后面调用， 可能会失败， 因为Fragment还没来得及加到Activity中就开始hook了。
 如果还有问题， 可以继续提出来。

**Comment by JeromeLydia** [comment]
你好 我在 basefragmet  中  resume  调用  崩溃了

**Comment by JeromeLydia** [comment]
![image](https://user-images.githubusercontent.com/20769572/64106016-e82de600-cda9-11e9-9aa2-42e071be4ab4.png)

**Comment by liys666666** [comment]
老哥，你要在Application先初始化呀。


---原始邮件---
发件人: &quot;JeromeLydia&quot;<notifications@github.com&gt;
发送时间: 2019年9月2日(星期一) 下午5:48
收件人: &quot;liys666666/DoubleClick&quot;<DoubleClick@noreply.github.com&gt;;
抄送: &quot;Comment&quot;<comment@noreply.github.com&gt;;&quot;liys&quot;<401654546@qq.com&gt;;
主题: Re: [liys666666/DoubleClick] 兼容性问题 (#4)




 
&mdash;

**Comment by JeromeLydia** [comment]
//自定义点击间隔时间(单位：毫秒)
 ViewDoubleHelper.init(this, 500);是这个吗?这个已经添加了，在activity  点击是可以用的！




------------------ 原始邮件 ------------------
发件人: "liys"<notifications@github.com>;
发送时间: 2019年9月2日(星期一) 下午5:59
收件人: "liys666666/DoubleClick"<DoubleClick@noreply.github.com>;
抄送: "平常人"<913974295@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [liys666666/DoubleClick] 兼容性问题 (#4)



老哥，你要在Application先初始化呀。 
 
 
 ---原始邮件--- 
 发件人: &quot;JeromeLydia&quot;<notifications@github.com&gt; 
 发送时间: 2019年9月2日(星期一) 下午5:48 
 收件人: &quot;liys666666/DoubleClick&quot;<DoubleClick@noreply.github.com&gt;; 
 抄送: &quot;Comment&quot;<comment@noreply.github.com&gt;;&quot;liys&quot;<401654546@qq.com&gt;; 
 主题: Re: [liys666666/DoubleClick] 兼容性问题 (#4) 
 
 
 
 
   
 &mdash;

**Comment by liys666666** [comment]
不好意思哈，我没考虑周全，那个方法只能在activity的resume后调用。因为初始化是在activity的resume里调的，所以会出现空指针的错误。


---原始邮件---
发件人: &quot;JeromeLydia&quot;<notifications@github.com&gt;
发送时间: 2019年9月2日(星期一) 晚上6:01
收件人: &quot;liys666666/DoubleClick&quot;<DoubleClick@noreply.github.com&gt;;
抄送: &quot;Comment&quot;<comment@noreply.github.com&gt;;&quot;liys&quot;<401654546@qq.com&gt;;
主题: Re: [liys666666/DoubleClick] 兼容性问题 (#4)


//自定义点击间隔时间(单位：毫秒) 
  ViewDoubleHelper.init(this, 500);是这个吗?这个已经添加了，在activity  点击是可以用的！ 
 
 
 
 
 ------------------ 原始邮&#x4EF6; ------------------ 
 发&#x4EF6;人: &quot;liys&quot;<notifications@github.com&gt;; 
 发送时间: 2019年9月2日(星期一) 下午5:59 
 收&#x4EF6;人: &quot;liys666666/DoubleClick&quot;<DoubleClick@noreply.github.com&gt;; 
 抄送: &quot;平常人&quot;<913974295@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 
 主题: Re: [liys666666/DoubleClick] 兼容性问题 (#4) 
 
 
 
 老哥，你要在Application先初始化呀。  
   
   
  ---原始邮&#x4EF6;---  
  发&#x4EF6;人: &amp;quot;JeromeLydia&amp;quot;<notifications@github.com&amp;gt;  
  发送时间: 2019年9月2日(星期一) 下午5:48  
  收&#x4EF6;人: &amp;quot;liys666666/DoubleClick&amp;quot;<DoubleClick@noreply.github.com&amp;gt;;  
  抄送: &amp;quot;Comment&amp;quot;<comment@noreply.github.com&amp;gt;;&amp;quot;liys&amp;quot;<401654546@qq.com&amp;gt;;  
  主题: Re: [liys666666/DoubleClick] 兼容性问题 (#4)  
   
   
   
   
     
  &amp;mdash;  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or mute the thread.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or mute the thread. 
&mdash;

**Comment by liys666666** [comment]
刚刚看错了，按理说应该是正常的啊，我这边都是没问题的， 刚刚发了一个V2.0.3版本你有空再试试
